<?php

namespace Database\Seeders\Admin;

use App\Models\Admin\Blog;
use App\Models\Admin\BlogCategory;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class BlogSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $blog_categories = array(
            array('id' => '2','slug' => 'about-us','name' => '{"language":{"en":{"name":"About us"},"es":{"name":null}}}','status' => '1','created_at' => '2023-09-21 09:17:24','updated_at' => '2023-09-21 09:17:24'),
            array('id' => '3','slug' => 'appointments','name' => '{"language":{"en":{"name":"Appointments"},"es":{"name":null}}}','status' => '1','created_at' => '2023-09-21 09:17:48','updated_at' => '2023-09-21 09:17:48'),
            array('id' => '4','slug' => 'service','name' => '{"language":{"en":{"name":"Service"},"es":{"name":null}}}','status' => '1','created_at' => '2023-09-21 09:18:00','updated_at' => '2023-09-21 09:18:00'),
            array('id' => '5','slug' => 'time-schedule','name' => '{"language":{"en":{"name":"Time Schedule"},"es":{"name":null}}}','status' => '1','created_at' => '2023-09-21 09:18:09','updated_at' => '2023-09-21 09:30:10')
        );
        BlogCategory::insert($blog_categories);

        //create blog
        $blogs = array(
            array('category_id' => '2','slug' => 'time-to-meet-our-great-staff-individuals','data' => '{"language":{"en":{"title":"Time to meet our great staff individuals!","description":"<p>Welcome to our eSalon\'s enriching blog, your digital haven for all things hair, beauty, and self-expression. Our team of experts is dedicated to providing you with a wealth of valuable insights, tips, and trends that go beyond the ordinary. Whether you\'re seeking guidance on maintaining healthy locks, exploring the latest hair color crazes, or in search of step-by-step tutorials for stunning hairstyles, our blog has you covered.<\\/p><ul style=\\"list-style-type:none;\\"><li>Free Download Instagram Logo<\\/li><li>Illustrator from Instagram Logo 9 Vectors svg vector collection<\\/li><li>Vectors SVG vector illustration graphic art design format.<\\/li><li>Following vectors are from the same pack as this vector also<\\/li><li>Instagram Logo SVG Vector is a part of Social Websites<\\/li><\\/ul><p>Delve into articles meticulously crafted to address your needs and curiosities. From decoding the secrets of achieving salon-worthy hair at home to uncovering the transformative power of a well-chosen hairstyle, we\'re committed to elevating your knowledge and confidence.<\\/p><blockquote><p>&nbsp;<\\/p><p><i>Producing Ideas Is The Main Way To Grow The Economy Life Insurance for Stay-at-Home Parents<\\/i><\\/p><p><i>JHON SMITH<\\/i><\\/p><\\/blockquote><p>Join us on this virtual journey of self-discovery and self-care. Whether you\'re a hair enthusiast, trendsetter, or simply someone looking to enhance their beauty routine, our blog is here to inspire, educate, and support you every step of the way. Our blog isn\'t just about aesthetics; it\'s about fostering a deeper connection between you and your hair, nurturing a sense of empowerment and self-assuredness. Experience the essence of our eSalon\'s dedication to your well-being and style evolution through our thoughtfully curated blog.<\\/p>","tags":["About Us","Hair Style"]},"es":{"title":null,"description":null}},"image":"seeder/blog1.webp"}','status' => '1','created_at' => '2023-09-21 09:59:37','updated_at' => '2023-09-21 09:59:37'),
            array('category_id' => '2','slug' => 'what-are-the-secrets-of-the-spa-why-like-us','data' => '{"language":{"en":{"title":"What are the secrets of the Spa & why like us.","description":"<p>Whether you\'re seeking guidance on maintaining healthy locks, exploring the latest hair color crazes, or in search of step-by-step tutorials for stunning hairstyles, our blog has you covered.<\\/p><ul style=\\"list-style-type:none;\\"><li>Free Download Instagram Logo<\\/li><li>Illustrator from Instagram Logo 9 Vectors svg vector collection<\\/li><li>Vectors SVG vector illustration graphic art design format.<\\/li><li>Following vectors are from the same pack as this vector also<\\/li><li>Instagram Logo SVG Vector is a part of Social Websites<\\/li><\\/ul><p>Delve into articles meticulously crafted to address your needs and curiosities. From decoding the secrets of achieving salon-worthy hair at home to uncovering the transformative power of a well-chosen hairstyle, we\'re committed to elevating your knowledge and confidence.<\\/p><blockquote><p>&nbsp;<\\/p><p><i>Producing Ideas Is The Main Way To Grow The Economy Life Insurance for Stay-at-Home Parents<\\/i><\\/p><p><i>JHON SMITH<\\/i><\\/p><\\/blockquote><p>Join us on this virtual journey of self-discovery and self-care. Whether you\'re a hair enthusiast, trendsetter, or simply someone looking to enhance their beauty routine, our blog is here to inspire, educate, and support you every step of the way. Our blog isn\'t just about aesthetics; it\'s about fostering a deeper connection between you and your hair, nurturing a sense of empowerment and self-assuredness. Experience the essence of our eSalon\'s dedication to your well-being and style evolution through our thoughtfully curated blog.<\\/p>","tags":["Color","Treatment"]},"es":{"title":null,"description":null}},"image":"seeder/blog2.webp"}','status' => '1','created_at' => '2023-09-21 10:02:23','updated_at' => '2023-09-21 10:02:23'),
            array('category_id' => '3','slug' => 'why-hairstyling-salon-is-the-tranquil-spot','data' => '{"language":{"en":{"title":"Why Hairstyling salon is the tranquil spot.","description":"<p>Seeking guidance on maintaining healthy locks, exploring the latest hair color crazes, or in search of step-by-step tutorials for stunning hairstyles, our blog has you covered.<\\/p><ul style=\\"list-style-type:none;\\"><li>Free Download Instagram Logo<\\/li><li>Illustrator from Instagram Logo 9 Vectors svg vector collection<\\/li><li>Vectors SVG vector illustration graphic art design format.<\\/li><li>Following vectors are from the same pack as this vector also<\\/li><li>Instagram Logo SVG Vector is a part of Social Websites<\\/li><\\/ul><p>Delve into articles meticulously crafted to address your needs and curiosities. From decoding the secrets of achieving salon-worthy hair at home to uncovering the transformative power of a well-chosen hairstyle, we\'re committed to elevating your knowledge and confidence.<\\/p><blockquote><p>&nbsp;<\\/p><p><i>Producing Ideas Is The Main Way To Grow The Economy Life Insurance for Stay-at-Home Parents<\\/i><\\/p><p><i>JHON SMITH<\\/i><\\/p><\\/blockquote><p>Join us on this virtual journey of self-discovery and self-care. Whether you\'re a hair enthusiast, trendsetter, or simply someone looking to enhance their beauty routine, our blog is here to inspire, educate, and support you every step of the way. Our blog isn\'t just about aesthetics; it\'s about fostering a deeper connection between you and your hair, nurturing a sense of empowerment and self-assuredness. Experience the essence of our eSalon\'s dedication to your well-being and style evolution through our thoughtfully curated blog.<\\/p>","tags":["Hair Cut"]},"es":{"title":null,"description":null}},"image":"seeder/blog3.webp"}','status' => '1','created_at' => '2023-09-21 10:59:34','updated_at' => '2023-09-21 10:59:59')
        );
        Blog::insert($blogs);
    }
}
