<?php

namespace Database\Seeders\Admin;

use App\Models\Admin\SiteSections;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Constants\SiteSectionConst;
use Illuminate\Support\Str;

class SiteSectionsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $data = array(
            array('key' => 'slider','value' => '{"items":{"65054e467093c":{"language":{"en":{"heading":"Gents And Women Stylish Parlour & Spa Center.","sub_heading":"The hairstyling parlor used to be something other than a spot to get another hairdo or a new trimmed - it was a public venue."},"es":{"heading":null,"sub_heading":null}},"id":"65054e467093c","status":1,"image":"seeder/slider1.webp","button_name":"Book Appointment"},"65054ee634515":{"language":{"en":{"heading":"Gents And Women Stylish Parlour & Spa Center.","sub_heading":"The hairstyling parlor used to be something other than a spot to get another hairdo or a new trimmed - it was a public venue."},"es":{"heading":null,"sub_heading":null}},"id":"65054ee634515","status":1,"button_name":"Book Appointment","image":"seeder/slider2.webp"},"65055421d908c":{"language":{"en":{"heading":"Gents And Women Stylish Parlour & Spa Center.","sub_heading":"The hairstyling parlor used to be something other than a spot to get another hairdo or a new trimmed - it was a public venue."},"es":{"heading":null,"sub_heading":null}},"id":"65055421d908c","status":1,"button_name":"Book Appointment","image":"seeder/slider3.webp"}}}','status' => '1','serialize' => NULL,'created_at' => '2023-09-16 05:13:34','updated_at' => '2023-09-16 07:08:34'),
            array('key' => 'how-its-work','value' => '{"language":{"en":{"title":"How It\'s Work","heading":"Follow our easy 4-step process","sub_heading":"It\'s simpler than you suspect. Follow 4 straightforward simple tasks."},"es":{"title":null,"heading":null,"sub_heading":null}},"items":{"6506920559a1e":{"language":{"en":{"item_title":"Create Account"},"es":{"item_title":null}},"id":"6506920559a1e","icon":"fas fa-user"},"650692f480aa8":{"language":{"en":{"item_title":"Search Parlour"},"es":{"item_title":null}},"id":"650692f480aa8","icon":"fas fa-search"},"6506932ec832e":{"language":{"en":{"item_title":"Select Parlour"},"es":{"item_title":null}},"id":"6506932ec832e","icon":"far fa-check-square"},"65069357c03a6":{"language":{"en":{"item_title":"Get Appointment"},"es":{"item_title":null}},"id":"65069357c03a6","icon":"fas fa-calendar"}}}','status' => '1','serialize' => NULL,'created_at' => '2023-09-16 09:12:10','updated_at' => '2023-09-17 05:49:31'),
            array('key' => 'testimonial','value' => '{"language":{"en":{"title":"Testimonials","heading":"What Our Client Says!","sub_heading":"Discover the voices of satisfaction. Our clients praise us for transformative experiences, personalized service, and exceptional expertise, making us their ultimate choice for hair and beauty."},"es":{"title":null,"heading":null,"sub_heading":null}},"items":{"65068abee5d92":{"language":{"en":{"comment":"\\u201cThey gives exceptional service, skilled stylists, and stunning results, testifying to our commitment to excellence.\\u201d"},"es":{"comment":null}},"id":"65068abee5d92","image":"seeder/testimonial1.webp","name":"Jon Newland","designation":"CEO, Company","rating":"4","created_at":"2023-09-17T05:12:30.983225Z"},"65068b5684284":{"language":{"en":{"comment":"\\u201cThey gives exceptional service, skilled stylists, and stunning results, testifying to our commitment to excellence.\\u201d"},"es":{"comment":null}},"id":"65068b5684284","image":"seeder/testimonial2.webp","name":"Angel Lonia","designation":"CEO, Company","rating":"3","created_at":"2023-09-17T05:15:02.548219Z"},"65068be845b92":{"language":{"en":{"comment":"\\u201cThey gives exceptional service, skilled stylists, and stunning results, testifying to our commitment to excellence.\\u201d"},"es":{"comment":null}},"id":"65068be845b92","image":"seeder/testimonial3.webp","name":"Davit Strom","designation":"CEO, Company","rating":"5","created_at":"2023-09-17T05:17:28.296728Z"},"65068c21d0a67":{"language":{"en":{"comment":"\\u201cThey gives exceptional service, skilled stylists, and stunning results, testifying to our commitment to excellence.\\u201d"},"es":{"comment":null}},"id":"65068c21d0a67","image":"seeder/testimonial4.webp","name":"Rodrigo De Paul","designation":"Software Engineer","rating":"4","created_at":"2023-09-17T05:18:25.862002Z"}}}','status' => '1','serialize' => NULL,'created_at' => '2023-09-17 05:11:45','updated_at' => '2023-09-17 05:18:25'),
            array('key' => 'statistic','value' => '{"items":{"6506a0afdd016":{"language":{"en":{"title":"Happy Customers"},"es":{"title":null}},"id":"6506a0afdd016","status":1,"counter_value":"71543","icon":"far fa-user-circle"},"6506a321a8aaa":{"language":{"en":{"title":"Get\'s Service"},"es":{"title":null}},"id":"6506a321a8aaa","status":1,"counter_value":"345","icon":"fas fa-american-sign-language-interpreting"},"6506a34786c5c":{"language":{"en":{"title":"Our Branches"},"es":{"title":null}},"id":"6506a34786c5c","status":1,"counter_value":"142","icon":"fas fa-code-branch"},"6506a370e8008":{"language":{"en":{"title":"Successful Customer"},"es":{"title":null}},"id":"6506a370e8008","status":1,"counter_value":"112232","icon":"fas fa-users"}}}','status' => '1','serialize' => NULL,'created_at' => '2023-09-17 06:27:46','updated_at' => '2023-09-17 06:57:52'),
            array('key' => 'photo-gallery','value' => '{"language":{"en":{"title":"Photo Gallery","heading":"Our eSalon Service Photo Gallery","sub_heading":"Dive into our mesmerizing photo gallery, where artistic vision meets skilled craftsmanship. Witness stunning transformations, curated styles, and exceptional hair artistry, inspiring your next eSalon visit."},"es":{"title":null,"heading":null,"sub_heading":null}},"items":{"650acc359d310":{"id":"650acc359d310","image":"seeder/photo-gallery1.webp","created_at":"2023-09-20T10:40:53.666983Z"},"650acc4382183":{"id":"650acc4382183","image":"seeder/photo-gallery2.webp","created_at":"2023-09-20T10:41:07.561601Z"},"650acc4d99d34":{"id":"650acc4d99d34","image":"seeder/photo-gallery3.webp","created_at":"2023-09-20T10:41:17.656139Z"},"650acc5799b91":{"id":"650acc5799b91","image":"seeder/photo-gallery4.webp","created_at":"2023-09-20T10:41:27.658671Z"},"650acc625392e":{"id":"650acc625392e","image":"seeder/photo-gallery5.webp","created_at":"2023-09-20T10:41:38.366020Z"},"650acc9510cb4":{"id":"650acc9510cb4","image":"seeder/photo-gallery6.webp","created_at":"2023-09-20T10:42:29.097591Z"},"650accac7c994":{"id":"650accac7c994","image":"seeder/photo-gallery7.webp","created_at":"2023-09-20T10:42:52.530930Z"}}}','status' => '1','serialize' => NULL,'created_at' => '2023-09-20 09:54:33','updated_at' => '2023-09-20 10:56:28'),
            array('key' => 'download-app','value' => '{"image":"seeder/download-app.webp","language":{"en":{"title":"Download App","heading":"Here Is Realtime Apk.","sub_heading":"Work with the pro, talented people at the most affordable price to get the most out of your time and cost using mobile apps.\\r\\n\\r\\nThe internet is saturated with applications from developers and creators worldwide. Sometimes it can be hard to tell which are the best downloaded apps on the market. Our list features an assortment of social media, antivirus, VPN, game, and emulator apps, to name a few. Don\\u2019t miss out on the latest Chrome, Bluetooth, Office, Youtube, and Web-cam file versions available today."},"es":{"title":null,"heading":null,"sub_heading":null}},"items":{"650a9e8289f72":{"language":{"en":{"item_title":"Get It On","item_heading":"Google Play"},"es":{"item_title":null,"item_heading":null}},"id":"650a9e8289f72","image":"seeder/google-play.webp","created_at":"2023-09-20T07:25:54.574488Z"},"650aa22ba97e9":{"language":{"en":{"item_title":"Download On The","item_heading":"Apple Store"},"es":{"item_title":null,"item_heading":null}},"id":"650aa22ba97e9","image":"seeder/apple-store.webp","created_at":"2023-09-20T07:41:31.703359Z"}}}','status' => '1','serialize' => NULL,'created_at' => '2023-09-20 07:02:55','updated_at' => '2023-09-20 07:41:31'),
            array('key' => 'footer','value' => '{"footer":{"language":{"en":{"description":"The hairstyling parlor used to be something other than a spot to get another hairdo or a new trimmed - it was a public venue."},"es":{"description":null}},"image":""},"social_links":[{"icon":"fab fa-facebook","link":"https:\\/\\/www.facebook.com\\/"},{"icon":"fab fa-twitter","link":"https:\\/\\/www.twitter.com\\/"},{"icon":"fab fa-instagram","link":"https:\\/\\/www.instagram.com\\/"},{"icon":"fab fa-linkedin-in","link":"https:\\/\\/www.linkedin.com\\/"}]}','status' => '1','serialize' => NULL,'created_at' => '2023-09-21 03:58:08','updated_at' => '2023-09-21 04:01:41'),
            array('key' => 'contact','value' => '{"schedules":[{"schedule":"Monday\\u2013Friday, 9am - 9pm"}],"language":{"en":{"title":"Request a Contact us","description":"Feel Free To Get In Touch With Us"},"es":{"title":null,"description":null}},"phone":"+03601 885399","address":"20-22 Wenlock Road, England, N1 7GU","email":"support@example.com","image":"seeder/contact.webp"}','status' => '1','serialize' => NULL,'created_at' => '2023-09-21 04:50:19','updated_at' => '2023-09-21 04:50:19'),
            array('key' => 'about','value' => '{"image":"seeder/about.webp","language":{"en":{"title":"About Our eSalon","heading":"\\"Discover Your Perfect Look: Unveiling the Essence of Beauty with eSalon\\".","sub_heading":"Welcome to eSalon, where beauty meets innovation. Our revolutionary platform offers a new era of personalized hair care. Through virtual consultations, our skilled stylists craft bespoke color formulations and regimens, tailored precisely to your preferences and needs. Experience the luxury of salon-quality transformations in the convenience of your own space"},"es":{"title":null,"heading":null,"sub_heading":null}},"items":{"650bd8c4ab1b0":{"language":{"en":{"item_title":"We provide best gents & women service."},"es":{"item_title":null}},"id":"650bd8c4ab1b0","created_at":"2023-09-21T05:46:44.700996Z"},"650bd8cf36019":{"language":{"en":{"item_title":"Our women parlour service great."},"es":{"item_title":null}},"id":"650bd8cf36019","created_at":"2023-09-21T05:46:55.221244Z"},"650bd8e604de9":{"language":{"en":{"item_title":"Add a new service Spa treatment."},"es":{"item_title":null}},"id":"650bd8e604de9","created_at":"2023-09-21T05:47:18.019985Z"}}}','status' => '1','serialize' => NULL,'created_at' => '2023-09-21 05:43:38','updated_at' => '2023-09-21 05:55:48'),
            array('key' => 'faq','value' => '{"image":"seeder/faq.webp","language":{"en":{"title":"FAQ Section","heading":"If you got questions we have answer."},"es":{"title":null,"heading":null}},"items":{"650be0966d9e6":{"language":{"en":{"question":"What is eSalon & how does it work?","answer":"eSalon is a cutting-edge platform delivering personalized virtual hair consultations and custom hair care solutions."},"es":{"question":null,"answer":null}},"status":1,"id":"650be0966d9e6"},"650be0b19cce3":{"language":{"en":{"question":"How to create an account eSalon account?","answer":"If you want to create an account on eSalon at frist go to account button and filup register form and submit information."},"es":{"question":null,"answer":null}},"status":1,"id":"650be0b19cce3"},"650be0c2670a7":{"language":{"en":{"question":"How to booking eSalon?","answer":"Visit our website, select your service, preferred date, and time, and complete your booking hassle-free with eSalon."},"es":{"question":null,"answer":null}},"status":1,"id":"650be0c2670a7"},"650be0db44d4f":{"language":{"en":{"question":"What type Spa treatment we are provide?","answer":"Indulge in rejuvenating massages, facials, body scrubs, and more, experiencing ultimate relaxation through our spa treatments."},"es":{"question":null,"answer":null}},"status":1,"id":"650be0db44d4f"}}}','status' => '1','serialize' => NULL,'created_at' => '2023-09-21 06:17:32','updated_at' => '2023-09-21 06:43:08'),
            array('key' => 'service','value' => '{"language":{"en":{"title":"Service Item","heading":"What type service we provide you."},"es":{"title":null,"heading":null}},"items":{"650bf0fcd600d":{"language":{"en":{"item_title":"Hairstyles","item_heading":"Discover our expertly crafted hairstyles, tailored to showcase your individuality and redefine your hair\'s beauty."},"es":{"item_title":null,"item_heading":null}},"status":1,"id":"650bf0fcd600d","icon":"fas fa-cut"},"650bf24090007":{"language":{"en":{"item_title":"Mustache Trim","item_heading":"Experience meticulous care with our precise mustache trims, enhancing your facial grooming to absolute sophistication."},"es":{"item_title":null,"item_heading":null}},"status":1,"id":"650bf24090007","icon":"fas fa-plane-departure"},"650bf255e5348":{"language":{"en":{"item_title":"Hair Cut","item_heading":"Revitalize your look with our professional haircuts, blending creativity and skill for a transformation you\'ll love."},"es":{"item_title":null,"item_heading":null}},"status":1,"id":"650bf255e5348","icon":"fas fa-cut"},"650bf278b6271":{"language":{"en":{"item_title":"Styling","item_heading":"Unlock personalized charm through our exquisite hair styling, where every strand tells a unique story."},"es":{"item_title":null,"item_heading":null}},"status":1,"id":"650bf278b6271","icon":"fas fa-female"},"650bf29284c05":{"language":{"en":{"item_title":"Treatment","item_heading":"Indulge in rejuvenating hair treatments, restoring health and radiance to your locks, leaving them revitalized."},"es":{"item_title":null,"item_heading":null}},"status":1,"id":"650bf29284c05","icon":"fas fa-briefcase-medical"},"650bf2a699e0b":{"language":{"en":{"item_title":"Color","item_heading":"Elevate your allure with our captivating hair color services, embracing vibrancy and self-expression flawlessly."},"es":{"item_title":null,"item_heading":null}},"status":1,"id":"650bf2a699e0b","icon":"fas fa-palette"},"650bf2c632ca0":{"language":{"en":{"item_title":"Facial","item_heading":"Indulge in luxurious hair facials, a fusion of relaxation and rejuvenation, leaving your hair gloriously revitalized."},"es":{"item_title":null,"item_heading":null}},"status":1,"id":"650bf2c632ca0","icon":"fas fa-grin"},"650bf2dd1e0bf":{"language":{"en":{"item_title":"Spa Massage","item_heading":"Embark on a journey of relaxation with our soothing spa massages, revitalizing your body and spirit."},"es":{"item_title":null,"item_heading":null}},"status":1,"id":"650bf2dd1e0bf","icon":"fas fa-spa"}}}','status' => '1','serialize' => NULL,'created_at' => '2023-09-21 07:04:16','updated_at' => '2023-09-21 07:38:25'),
            array('key' => 'blog','value' => '{"language":{"en":{"title":"Web Journal","heading":"Meet some of our latest Web Journal","sub_heading":"At Stuff Movements, consumer loyalty is vital to us. Look into our most recent study and see what our clients are talking about us."},"es":{"title":null,"heading":null,"sub_heading":null}}}','status' => '1','serialize' => NULL,'created_at' => '2023-09-21 09:05:54','updated_at' => '2023-09-21 09:05:54')
        );
        SiteSections::insert($data,['key'],['value','status']);
    }
}
